### ISSUE TITLE
The API looks stable enough for a v1.0.0

### ISSUE THREAD

**Issue by tomekwi** [dominictarr/parse-regexp#2]
Isn’t it?

I’m always a bit wary of `0.x` packages, and even more wary of `0.0.x`. According to semver you could change the API any time.

But the thing looks simple and mature :) Can you bump to v1.0.0?

**Comment by dominictarr** [comment]
okay okay, well 0.0 doesn't really mean anything apart from that the author hasn't added any features, or made any breaking changes. it doesn't necessarily mean it's unstable.

**Comment by tomekwi** [comment]
Well yes and no – because semver 2.0 says “Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.”

So if we stick to semver, I should lock down this dependency to be sure I don’t run into incompatibility.

**Comment by dominictarr** [comment]
that is the worst part of semver. conflating how your interfaces change with what stability they have is silly. I just document whether it's been a breaking, feature, or backwards compatible patch. If you really need to communicate whether it's stable or not put that in the documentation.

**Comment by tomekwi** [comment]
I actually find it quite useful. Otherwise some of my modules would end up at *v8.0* once they’ve passed their experimental phase.

If you know an API isn’t going to change, you can publish the initial version at *v1.0.0* and not suffer from this “worst part”.

**Comment by dominictarr** [comment]
What is wrong with _8.0_ ?

Btw, i have written over 400 modules and i only have a tiny handful that are greater than 5 major changes.

You could argue, that this is a more reliable indicator than 1.0.
because 1.0 only means that the _author thinks_ it's now stable.
how can they know they are not gonna have a better idea later?
they do not. however, if they are honest about their changes.
then you can see that a version number like 7 may indicate they
have put a lot of work into that module.

**Comment by tomekwi** [comment]
True. There’s nothing wrong with that. I guess much of this depends on personal style.

**Comment by tomekwi** [comment]
After some time I admit you’re right. It makes no sense to mark a library as “unstable” when releasing it in the open. People are going to use it, and *if* there really is a breaking change, it’s good if the version number holds that info from the very first release.

Looking at my (well under 400) libraries, I see that even though I protectionally started out with an “unstable” `0.x` tag, there have rarely really been breaking changes since then.

Since I still want to keep to semver, I started tagging the initial release of a library as `1.0.0`.

I still think the “`0.x` = unstable” convention may sometimes make sense for apps or tools. But it looks like open-source libraries are better off starting out with a `1.0.0` and keeping to the breaking-feature-fix semantics from the very beginning.

**Comment by dominictarr** [comment]
Cool yes, starting at 1.0.0 is totally fine

**Comment by tomekwi** [comment]
:)

All in all, do whatever you want. Bump if you want, and just ignore this if you don’t.

**Comment by tomekwi** [comment]
> that is the worst part of semver

@dominictarr, I’ve just run into a serious problem when maintaining an old 0.x.x version of a project which “accidentally” sprang into LTS mode.

So I can’t agree more!
